### ISSUE TITLE
Warthog w/ "Hawk" ability

### ISSUE THREAD

**Issue by Obi-BenKenobi** [Baledin/FlyCasual#83] opened 2024-12-06 06:58 UTC
**Fly Casual Release Version**
V2.5.20241102.02

**Online Game Mode**
No

**Describe the bug**
When flying "Warthog" in the Clone Z-95 Headhunter, at the start of the end phase, the "Hawk" ability prompt appears as if you were flying that pilot instead.

**To Reproduce**
1. Fly "Warthog" in Z-95 Headhunter
2. Initiate the End Phase

**Expected behavior**
- Warthog should not have "Hawk" ability.

**Screenshots**
Attached

**Platform/Device (be as specific as possible):**
 - OS: Android
 - Version 14

**Additional context**
There may be other Z-95 pilots that have this same error as well.
![Screenshot_20241204_162159_Fly Casual](https://github.com/user-attachments/assets/ca2f522e-9edb-4783-be68-2af2644be1b7)

**Comment by Baledin** [comment] 2024-12-06 15:06
Duplicate of #85.

**Closed as completed by Baledin** 2024-12-06 15:06 UTC
