### ISSUE TITLE
New Obstacle Rules

### ISSUE THREAD

**Issue by quall3** [Baledin/FlyCasual#14] opened 2024-03-16 16:36 UTC
** Fly Casual Release Version **
all

**Describe the bug**
Old obstacle rules are still implemented.

New Rules should be:

If a ship moves through or overlaps an obstacle, it suffers an effect based on 
the type of obstacle after resolving its move: 
• Asteroid: The ship suffers one  damage. Roll one attack die. On a 
hit or crit result, the ship suffers an additional damage.
• Blaze: Roll one attack die. On a hit or crit result, the ship suffers one 
damage; on a eyeball result, it gains one stress token. Then the ship 
skips its Perform Action step this round.
• Debris Cloud: The ship is assigned one stress token. Roll one attack 
die. On a hit result, the ship suffers one  damage. On a crit result, the 
ship suffers one crit damage.
• Electro-Chaff Cloud: The ship breaks all its locks and all locks on it 
and then is assigned one jam token. Roll one attack die. On a hit or crit
result, the ship is assigned one stress token.
• Gas Cloud: The ship breaks all its locks and all locks on it and then is 
assigned one strain token. Roll one attack die. On a hit result, the ship 
is assigned one ion token. On a crit result, the ship is assigned three ion 
tokens.
• Loose Cargo: The ship is assigned one strain token. Roll one attack 
die. On a hit or crit result, the ship is assigned one stress token.
• Spare Parts: The ship is assigned one strain token. Roll one attack 
die. On a hit or crit Result, the ship is assigned one stress token.
• If a ship ends a maneuver overlapping an obstacle, it skips its Perform 
Action step.

Before a ship moves, if it is at range 0 of an obstacle, it does not suffer 
the effects of that obstacle unless it overlaps that obstacle again.

While a ship is at range 0 of an obstacle it may suffer different effects.
Gas Cloud: The ship cannot acquire locks and cannot be locked. The 
ship cannot perform attacks.

Gas clouds do not allow to turn 1 blank to an evade when obstructing a shot.

**Comment by quall3** [comment] 2024-03-16 16:37
Also, please implement the pride of mandalore obstacle shapes.

**Comment by Baledin** [comment] 2024-11-15 18:13
Pride of Mandalore asteroids - commit 770b968.
Validated Asteroid and Debris Clouds, appear to be working as intended (@quall3, please confirm that these two do work as expected).

**Comment by Baledin** [comment] 2024-11-23 16:46
Created new Loose Cargo debris type for Loose Cargo and Spare Parts. Set these up to be spawned by the appropriate upgrade.
Gas Clouds now break locks and prevent new locks while landed on them.

**Comment by Baledin** [comment] 2024-11-23 16:47
Blaze and Electro-Chaff cloud will be incorporated into the appropriate upgrades work. Closing this issue as remaining work has been completed.

**Closed as completed by Baledin** 2024-11-23 16:47 UTC
Labels: bug
