### ISSUE TITLE
Repulsorlift Stabilizers Sideslip implements on wrong side

### ISSUE THREAD

**Issue by Baledin** [Baledin/FlyCasual#105] opened 2024-12-27 16:13 UTC
**Fly Casual Release Version**
v2.5.20241101.02

**Online Game Mode**
No

**Describe the bug**
When using a HMP Droid Gunship and have Repulsorlift Stabilizers Active, selecting a left turn maneuver sideslips to the right instead of the left. This may be happening for banks as well.

**To Reproduce**
1. Have HMP Droid Gunship on roster
2. Perform a straight maneuver and select yes to flip Repulsorlift Stabilizers to Active
3. Select a turn maneuver, left does a right sideslip and vice versa

**Expected behavior**
When selecting a left maneuver, the sideslip should be on the left.

**Comment by quall3** [comment] 2024-12-31 07:43
Yoou can close this. it is workig as intended in current release. A left turn is put to thehright side of the ship. 
the direction of the maneuver stays the same, its just aligned to the side. 
check the rules for sideslip again ;)

**Comment by Baledin** [comment] 2024-12-31 17:30
Thanks, don't know why I didn't think to check the rules reference on this. It just feels so wrong to choose left and to place it on the right side.

**Closed as completed** 2024-12-31 17:30 UTC
Labels: bug
